import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login': 'Login',
          'register': 'Register',
          'home': 'Home',
          'profile': 'Profile',
          'history': 'History',
          'all_purchase': 'All Purchases',
          'all_sell': 'All Sells',
          'employee': 'Employee',
          'change_language': 'Change Languege',
          'do_you_want_to_logout': 'Do you want to logout?',
          'cancel': 'Cancel',
          'confirm': 'Confirm',
          'total': 'Total',
          'items': 'Items',
          'qty': 'Qty',
          'total_money': 'Totam Money',
          'date': 'Date',
          'day': 'Day',
          'month': 'Month',
          'year': 'Year',
          'start_date': 'Start Date',
          'end_date': 'End Date',
          'bill_no': 'Bill no',
          'payment_type': 'Payment Type',
          'cash': 'Cash',
          'bank_transfer': 'bank_Transfer',
          'search': 'Search',
          'customer': 'Customer',
          'not_account': 'Not Account yet',
          'has_account': 'Has Account',
          'password': 'Password',
          'phone': 'Phone',
          'village': 'Village',
          'district': 'District',
          'province': 'Province',
          'edit': 'Edit',
          'firstname': 'Firstname',
          'lastname': 'Lastname',
          'confirm_password': 'Confirm Password',
          'new_product': 'New Product',
          'advice_product': 'Advice Product',
          'all_product': 'All Product',
          'lak': 'Lak',
          'not_found_data': 'Not found data',
          'new': 'New',
          'order_list': 'Order List',
          'checkout': 'Check Out',
          'please_enter_all': 'Please enter all',
          'password_not_match': 'Confirm password not match',
          'something_went_wrong': 'Sonething went wrong',
          'logout': 'Logout',
          'prefix': 'Prefix',
          'phone_is_already': 'Phone is already',
          'success': 'Success',
          'phone_or_password_incorrect': 'Phone or password is incorrect',
          'lao': 'Lao',
          'english': 'English',
          'username_id_already': 'Username is already',
          'grand_total': 'Grand Total',
          'choose_current_address': 'Choose Current Address',
          'fullname': 'Fullname',
          'thank_you': 'Thank you',
          'back': 'Back',
          'booking': 'New Booking',
          'detail': 'Detail',
          'add_to_cart': 'Add to cart',
          'popular_product': 'Popular products',
          'save_qrcode_sn': 'Save QRCODER SN',
          'use_current_address': 'Use Current Address',
          'branch': 'Branch',
          'booking_list': 'Booking list',
          'detail_booking': 'Detaill booking',
          'scan_out': 'Scan Out',
          'confirm_sale': 'Confirm Sale',
          'qrcode_sn_multiple': 'Duplicate QRCODE SN',
          'can_not_scan_out_full_serial_number':
              'The number of QRCODE SN is complete',
          'product_list': 'ລາຍການສິນຄ້າ',
          'delivery': 'Deliverd',
          'do_you_want_to_confirm_sale_or_not':
              'Do you want to confirm sale or not?',
          'bill_get_money': 'Receive Bill',
          'thankyou': 'Thank you!',
          'staff': 'Staff',
          'do_you_want_to_confirm': 'Do you want to confirm?',
          'please_scan_qrcode_sn_full': 'Please scan QRCODE SN',
          'to': 'To',
          'do_you_want_to_confirm_delete_serial_number':
              'Do you want to delete QRCODE SN?',
          'all': 'All',
          'new_version_update_available': 'New version update available',
          'please_update_this_app_version': 'Please update this app version',
          'update': 'Update',
          'location': 'Show Location',
          'scan_qrcode_sn': 'SCAN QRCODE SN',
          'do_you_want_to_save_qrcode_sn': 'Do you want to save QRCODE SN ບໍ?',
          'approved': 'Approved',
          'waiting_approve': 'Waiting approve',
          'please_select_customer': 'Please select customer',
          'category': 'Category',
          'view_all': 'View all',
          'select_customer': 'Select customer',
          'purchase_with_branch': 'Ever bought at any branch?',
          'please_select_branch': 'Please select branch',
          'type_of_use': 'Type Of Use',
          'please_select_type_of_use': ' Please select type of use',
          'male': 'Male',
          'female': 'Female',
          'not_specify': 'Not_specify',
          'product_detail': 'Product details',
          'welcome': 'Welcome',
          'cn': 'Chinese',
          'loan_goal': 'Loan goals',
          'arrears_total': 'Arrears total',
          'arrears': 'Arrears',
          'paid': 'Paid',
          'loan': 'Loan',
          'instalment': 'Instalments',
          'contact_us': 'Contact Us',
          'language': 'Language',
          'username': 'Username',
          'product': 'Product',
          'supplier': 'Supplier',
          'save': 'Save',
          'select_payment_image': 'Select the payment image',
          'picture_problem': 'Picture of the machine with the problem',
          'personal_information': 'Personal Information',
          'is_being_delivered': ' is being delivered',
          'discount': 'Discount',
          'thb': 'THB',
          'usd': 'USD',
          'cny': 'CNY',
          'address': 'Address',
          'payment': 'Payment',
          'add_picture_problem': 'Add picture problem',
          'amount': 'Amount',
          'currency': 'currency',
          'money_return': 'Money return',
          'Select_payment_currency': 'Select payment currency',
          'add_payment': 'Add payment',
          'balance': 'Balance',
          'next': 'Next',
          'ordered': 'Ordered',
          'packed': 'Packed',
          'shipped': 'Shipped',
          'delivered': 'Delivered',
          'Add_prepayment': 'Add prepayment',
          'Add_the_problem_image': 'Add the problem image',
          'slip_payment': 'Slip payment',
          'problem_image': 'Problem Image',
          'Send_machine': 'Send machine',
          'due': 'Due',
          'partial': 'Partial',
          'status': 'Status',
          'profit': 'Profit',
          'note': 'Note',
          'current_stock': 'Current stock',
          'selling_price': 'Selling price',
          'failed': 'Failed',
          'sent': 'Sent',
          'please_select_issue_product': 'please select issue product',
          'return': 'Return',
          'do_you_want_save_or_not': 'Do you want to save or not?',
          'received_money': 'Received money',
          'check_before_confirm': 'Check before confirm',
          'unauthorized_action': 'Unauthorized action.',
          'check_before_receive_money': 'Check before receive money',
          'receive_money': 'Receive money',
          'check_before_confirm_success': 'Check before confirm success',
          'product_warehouse': 'Product warehouse',
          'number_production': 'Number production',
          'issue': 'Issue',
          'Choose_problem_product': 'Choose problem product',
          'delivery_person': 'Delivery person',
          'Tuition_fees': 'Tuition',
          'score': 'Score',
          'student': 'Student',
          'total_paid': 'Total Paid',
          'total_debt': 'Total Debt',
          'ok': 'Ok',
          'logouts_successfully': 'Logout success',
          'create_date': 'Create Date',
          'label_code': 'Label Code',
          'special_discount': 'Special discount',
          'school_mina': 'School Mina',
          'age': 'Age',
          'birtdaydate': 'BirtdayDate',
          'class': 'Class',
          'missing_school': 'Missing Schools',
          'activities': 'Activities',
          'code_bill': 'Code bill',
          'password_do_not_match': 'Password do not match',
          'select': 'Select',
          'select_year': 'Select years',
          'select_month': 'Select month',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'corrected_successfully': 'Corrected successfully',
          'invalid_phone_number_or_password_please_try_again':
              'Invalid phone number or password! Please try again...',
          'class_room': 'Class room',
          'not_yet': 'Not yet',
          'waiting_confirm': 'Waiting confirm',
          'got_it': 'Got it',
          'give_money': 'Giv money',
          'administration': 'Administration',
          'subject': 'Sub ject',
          'start_pay': 'Start pay',
          'end_pay': 'End pay',
          'email': 'Email',
          'gender': 'Gender',
          'other': 'Other',
          'select_classe': 'Select classes',
          'select_subject': 'Select subject',
          'score_added_successfully': 'Score added successfully',
          'please_select_subject_first': 'Please select a subject first.',
          'please_add_information': 'Please add information.',
          'please_enter_complete_information':
              'Please enter complete information!',
          'develop': 'Develop',
          'add_inforamtion': 'Add informations.',
          'monthly': 'Monthly',
          'no': 'No',
          'setting': 'Settings',
          'childrens_score': 'Children scores',
          'score_details': 'Monthly score details',
          'teacher': 'Teacher',
          'music': 'Music (Practical)',
          'drawing': 'Drawing (Practical)',
          'computer': 'Computer (Practical)',
          'account': 'Account',
          'total_score': 'Total score',
          'average_score': 'Average score',
          'edit_profile': 'Edit profile',
          'upload_photo': 'Upload a photo',
          'delete': 'Delete',
          'are_you_sure_you_want_to_delete_this_item':
              'Are you sure you want to delete this item?',
          'confirm_delete': 'Confirm Delete',
          'select_student': 'Select student',
          'select_type': 'Select type',
          'dated': 'Dated',
          'score_cut_out': 'Score cut out',
          'reset': 'Reset',
          'date_is_required': 'Date is required!',
          'follow_lack_off': 'Follow lack off',
          'follow_lack_off_details': 'Details on tracking absences',
          'student_name': 'Student name',
          'type': 'Type',
          'creator': 'Creator',
          'total_score_cut_out': 'Total score cut out',
          'missing_the_morning': 'Missing the morning',
          'missing_evening': 'Missing evening',
          'missing_all_day': 'Missing all day',
          'classe': 'Classe',
          'parent': 'Parent',
          'search_month_year': 'Search month year',
          'Payment_amount': 'Payment amount',
          'transfer': 'Transfer',
          'take_children': 'Take children',
          'Missing_school': 'Missing school',
          'Pay_tuition_fees': 'Pay tuition fees',
          'payment_history': 'Payment history',
          'notification': 'Notification',
          'waiting': 'Waiting',
          'car_number': 'Car number',
          'delete_successfully': 'Deleted successfully.',
          'no_information_found': 'No information found.',
          'update_failed': 'Update failed.',
          'Select_child_adopt': 'Choose a child to adopt.',
          'call_children': 'Call children',
          'download': 'Download',
          'Please_scan_the_QRCode_to_pay_your_tuition':
              'Please scan the QRCode to pay your tuition.',
          'Waiting_for_payment': 'Waiting for payment',
          'check_student': 'Check student',
          'sorry': 'Sorry',
          'No_data_in_the_system': 'No data in system',
          'called': 'Called',
          'No_information_yet': 'No information yet',
          'Get_discount_policy': 'Get discount policy',
          'school': 'School',
          'select_school': 'Select school',
          'nick_name': 'Nick name',
          'send_students': 'Send students',
          'religion': 'Religion',
          'nationality': 'Nationality',
          'group_language': 'Group language',
          'ethnicity': 'Ethnicity',
          'special_health': 'Special health condition',
          'personal_talent': 'Personal talent',
          'living': 'Place of residence',
          'SelectClass_group': 'SelectClass group',
          'Select_Class': 'Select Class',
          'parent_data': 'Parent information (name, address...)',
          'parent_contact':
              'Parent contact information (phone number, app, Facebook, email...)',
          'or': 'Or',
          'people': 'People',
          'income': 'Income',
          'expenses': 'Expenses',
          'balance_income': 'Balance',
          'opened': 'Opened',
          'closed': 'Closed',
          'outstanding_tuition_fees': 'Overdue tuition fees',
          'select_package': 'Select packages',
          'school_name': 'School name',
          'School_owner': 'School owner',
          'Not_Found_QR_Code_Payment': 'Not Found QR Code Payment',
          'Start_paying': 'Start paying',
          'Due_date': 'Due date',
          'Contract_renewal': 'Contract renewal',
          'price': 'Price',
          'Blood_type': 'Blood type',
          'Education_system': 'Education system',
          'Education_level': 'Education level',
          'Specialization': 'Specialization',
          'Graduated_from_school': 'Graduated from school',
          'School year system': 'School year system',
          'End_of_the_year': 'End of the year',
          'Duties': 'Duties',
          'salary': 'Salary',
          'job': 'Job',
          'job_address': 'Job address',
          'job_position': 'Job position',
          'select_pay': 'Select to pay',
          'QR_code_download_complete': 'QR code Payment download complete',
          'Destination_bank': 'Destination bank',
          'LAPNet_reference_number': 'LAPNet reference number',
          'version': 'Version',
          'Delete_Account': 'Delete Account',
          'Confirm_Account_Deletion': 'Confirm Account Deletion',
          'des_confirm_delete_account':
              'Are you sure you want to permanently delete your account? This action cannot be undone.',
          'total_income': 'Total income',
          'Contract_management': 'Contract management',
          'check_payment': 'Check payment',
          'QR_Code_valid_within_hour': 'QR Code valid within 1 hour',
          'This_bill_has_not_been_paid_yet': 'This bill has not been paid yet',
          'Track_absences': 'Track absences',
          "Still_left": "Still left",
          "Minute": "Minute",
          "Seconds": "Seconds",
          'bill_number': 'Bill number',
          'Adjust': 'Adjust',
          'Please_pay_the_tuition_fee': 'Please pay the tuition fee',
          'Total_income_plan': 'Total income plan',
          'Do_you_want_to_allow_new_notifications': 'Do you want to allow new notifications',
          'transaction': 'Transaction',
          'scan-in-out': 'Scan in-out',
          'check_in': 'Check In',
          'check_out': 'Check Out',
          'request_go_home': 'Request go home',
          'who_go_with': 'Choose who the student goes with',
          'time_in': 'Time In',
          'time_out': 'Time Out',
          'Click_in-out': 'Click in-out',
          'your_current_position': 'Your current position',
          'academic_year': 'Academic year',
          'scan': 'Scan',
          'history_missing_school': 'History missing school',
          'check_in_check_out': 'Checkin-checkout school',
          'scan_in': 'Scan in',
          'IN': 'IN',
          'OUT': 'OUT',
          'aLl_score': 'ALl score',
          'score_cuted': 'Score cuted',
        },
        'la_LA': {
          'login': 'ເຂົ້າສູ່ລະບົບ',
          'register': 'ລົງທະບຽນ',
          'home': 'ໜ້າຫຼັກ',
          'profile': 'ໂປຣໄຟລ໌',
          'history': 'ການເຄື່ອນໄຫວ',
          'all_purchase': 'ຍອດສັ່ງຊື້ທັງໝົດ',
          'all_sell': 'ຍອດຂາຍທັງໝົດ',
          'employee': 'ພະນັກງານ',
          'change_language': 'ປ່ຽນພາສາ',
          'do_you_want_to_logout': 'ທ່ານຕ້ອງການອອກຈາກລະບົບບໍ?',
          'cancel': 'ຍົກເລີກ',
          'confirm': 'ຢືນຢັນ',
          'total': 'ຍອດລວມ',
          'items': 'ລາຍການ',
          'qty': 'ຈໍານວນ',
          'total_money': 'ລວມເງິນ',
          'date': 'ວັນທີ',
          'day': 'ມື້',
          'month': 'ເດືອນ',
          'year': 'ປີ',
          'start_date': 'ວັນທີເລີ່ມ',
          'end_date': 'ວັນທີສິ້ນສຸດ',
          'bill_no': 'ລະຫັດໃບບິນ',
          'payment_type': 'ຮູບແບບຊໍາລະ',
          'cash': 'ເງິນສົດ',
          'bank_transfer': 'ເງິນໂອນ',
          'search': 'ຄົ້ນຫາ',
          'customer': 'ລູກຄ້າ',
          'not_account': 'ຍັງບໍໍ່ທັນມີບັນຊີ*',
          'has_account': 'ຫຼືມີບັນຊີ*',
          'password': 'ລະຫັດຜ່ານ',
          'phone': 'ເບີໂທ',
          'village': 'ບ້ານ',
          'district': 'ເມືອງ',
          'province': 'ແຂວງ',
          'username': 'ຊື່ຜູ້ໃຊ້ລະບົບ',
          'edit': 'ແກ້ໄຂ',
          'firstname': 'ຊື່',
          'lastname': 'ນາມສະກຸນ',
          'confirm_password': 'ຢືນຢັນລະຫັດຜ່ານ',
          'new_product': 'ສິນຄ້າອອກໃໝ່',
          'advice_product': 'ສິນຄ້າແນະນໍາ',
          'all_product': 'ສິນຄ້າທັງໝົດ',
          'lak': 'ກີບ',
          'not_found_data': 'ຍັງບໍ່ມີຂໍ້ມູນ',
          'new': 'ໃໝ່',
          'order_list': 'ລາຍການສັ່ງຈອງ',
          'checkout': 'ຊໍາລະເງິນ',
          'please_enter_all': 'ກະລຸນາໃສ່ຂໍ້ມູນໃຫ້ຄົບ',
          'password_not_match': 'ລະຫັດຢືນຢັນບໍ່ຖືກຕ້ອງ',
          'something_went_wrong': 'ມີບາງຢ່າງຜິດພາດ',
          'logout': 'ອອກລະບົບ',
          'prefix': 'ທ້າວ/ນາງ',
          'phone_is_already': 'ເບີໂທນີ້ມີໃນລະບົບແລ້ວ',
          'success': 'ສໍາເລັດແລ້ວ',
          'phone_or_password_incorrect': 'ເບີໂທ ຫຼື ລະຫັດຜ່ານ ບໍ່ຖືກຕ້ອງ!',
          'lao': 'ລາວ',
          'english': 'ອັງກິດ',
          'username_id_already': 'ຊື່ຜູ້ໃຊນີ້ມີໃນລະບົບແລ້ວ',
          'grand_total': 'ລວມເປັນເງິນ',
          'choose_current_address': 'ເລືອກທີ່ຢູ່ປັດຈຸບັນ',
          'fullname': 'ຊື່ ແລະ ນາມສະກຸນ',
          'thank_you': 'ຂໍຂອບໃຈ',
          'back': 'ກັບຄືນ',
          'booking': 'ສັ່ງຈອງໃໝ່',
          'detail': 'ລາຍລະອຽດ',
          'add_to_cart': 'ເພີ່ມເຂົ້າກະຕ່າ',
          'popular_product': 'ສິນຄ້າຍອດນິຍົມ',
          'save_qrcode_sn': 'ບັນທຶກ QRCODE SN',
          'use_current_address': 'ໃຊ້ທີ່ຢູ່ປັດຈູບັນ',
          'branch': 'ສາຂາ',
          'booking_list': 'ລາຍການສັ່ງຈອງ',
          'detail_booking': 'ລາຍລະອຽດສັ່ງຈອງ',
          'scan_out': 'ສະແກນອອກ',
          'confirm_sale': 'ຢືນຢັນຂາຍ',
          'qrcode_sn_multiple': 'QRCODE SN ຊໍ້າກັນ',
          'can_not_scan_out_full_serial_number': 'ຈໍານວນ QRCODE SN ຄົບແລ້ວ',
          'product_list': 'Product',
          'delivery': 'ກໍາລັງຈັດສົ່ງ',
          'do_you_want_to_confirm_sale_or_not':
              'ທ່ານຕ້ອງການຢຶນຢັນຂາຍ ນີ້ ຫຼື ບໍ່?',
          'bill_get_money': 'ໃບບີນເກັບເງິນ',
          'thankyou': 'ຂໍຂອບໃຈທີ່ທ່ານມາອຸດໜູນ',
          'staff': 'ພະນັກງານ',
          'do_you_want_to_confirm': 'ທ່ານຕ້ອງການຢືນຢັນແທ້ ຫຼື ບໍ?',
          'please_scan_qrcode_sn_full': 'ກະລຸນາສະແກນ QRCODE SN ໃຫ້ຄົບກ່ອນ!',
          'to': 'ຫາ',
          'do_you_want_to_confirm_delete_serial_number':
              'ທ່ານຕ້ອງການລຶບ QRCODE SN ນີ້ບໍ?',
          'all': 'ທັງໝົດ',
          'new_version_update_available': 'ມີການອັບເດດເວີຊັ່ນໃຫມ່',
          'please_update_this_app_version': 'ກະລຸນາອັບເດດເວີຊັ່ນ',
          'update': 'ອັບເດດ',
          'location': 'ສະແດງແຜນທີ່',
          'scan_qrcode_sn': 'ສະແກນ QRCODE SN',
          'do_you_want_to_save_qrcode_sn': 'ທ່ານຕ້ອງການບັນທຶກ QRCODE SN ບໍ?',
          'approved': 'ອະນຸມັດແລ້ວ',
          'waiting_approve': 'ລໍຖ້າອະນຸມັດ',
          'please_select_customer': 'ກະລຸນາເລືອກລູກຄ້າ',
          'category': 'ໝວດໝູ່ສິນຄ້າ',
          'view_all': 'ເບິ່ງທັງໝົດ',
          'select_branch': 'ເລືອກສາຂາ',
          'purchase_with_branch': 'ເຄີຍຊື້ຢູ່ສາຂາໃດ?',
          'please_select_branch': 'ກະລຸນາເລືອກສາຂາກ່ອນ',
          'type_of_use': 'ປະເພດການໃຊ້ງານ',
          'please_select_type_of_use': 'ກະລຸນາເລືອກປະເພດການໃຊ້ງານ',
          'select_customer': 'ເລືອກລູກຄ້າ',
          'male': 'ຊາຍ',
          'female': 'ຍິງ',
          'not_specify': 'ບໍ່ລະບຸ',
          'product_detail': 'ລາຍລະອຽດສິນຄ້າ',
          'welcome': 'ຍິນດີຕ້ອນຮັບ',
          'cn': 'ຈີນ',
          'loan_goal': 'ເປົ້າໝາຍເງິນກູ້',
          'arrears_total': 'ຍອດຄ້າງຊໍາລະ',
          'arrears': 'ຍອດຄ້າງຊໍາລະ',
          'paid': 'ຊໍາລະແລ້ວ',
          'loan': 'ເງິນກູ້ຢືມ',
          'instalment': 'ງວດ',
          'contact_us': 'ຕິດຕໍ່ພວກເຮົາ',
          'language': 'ພາສາ',
          'product': 'ສິນຄ້າ',
          'supplier': 'ຜູ້ຈໍາໜ່າຍ',
          'save': 'ບັນທຶກ',
          'select_payment_image': 'ເລືອກຮູບຊໍາລະເງິນ',
          'picture_problem': 'ຮູບເຄື່ອງທີ່ມີບັນຫາ',
          'personal_information': 'ຂໍ້ມູນສ່ວນຕົວ',
          'is_being_delivered': 'ກໍາລັງຈັດສົ່ງ',
          'discount': 'ສ່ວນຫຼຸດ',
          'thb': 'ບາດ',
          'usd': 'ໂດລາ',
          'cny': 'ຢວນ',
          'address': 'ທີ່ຢູ່',
          'payment': 'ຊໍາລະເງິນ',
          'add_picture_problem': 'ເພີ່ມຮູບທີ່ມີບັນຫາ',
          'amount': 'ຈໍານວນເງິນ',
          'currency': 'ສະກຸນເງິນ',
          'money_return': 'ເງິນທອນຄືນ',
          'Select_payment_currency': 'ເລືອກສະກຸນເງິນ ຊໍາລະເງິນ',
          'add_payment': 'ເພີ່ມການຊໍາລະ',
          'balance': 'ຍອດຄ້າງ',
          'next': 'ຕໍ່ໄປ',
          'ordered': 'ຈອງເຄື່ອງ',
          'packed': 'ຫ້ອມຫໍ່',
          'shipped': 'ຈັດແລ້ວ',
          'delivered': 'ສົ່ງສໍາເລັດ',
          'Add_prepayment': 'ເພີ່ມການຊໍາລະເງິນກ່ອນ',
          'Add_the_problem_image': 'ເພີ່ມຮູບທີ່ມີບັນຫາ',
          'slip_payment': 'ໃບຊໍາລະເງິນ',
          'problem_image': 'ຮູບທີ່ມີບັນຫາ',
          'Send_machine': 'ສົ່ງເຄື່ອງ',
          'due': 'ຈົດໜີ້',
          'partial': 'ຊໍາລະບາງສ່ວນ',
          'status': 'ສະຖານະ',
          'profit': 'ກໍາໄລ',
          'note': 'ໝາຍເຫດ',
          'current_stock': 'ສາງປະຈຸບັນ',
          'selling_price': 'ລາຄາຂາຍ',
          'failed': 'ບໍ່ສໍາເລັດ',
          'sent': 'ສົ່ງແລ້ວ',
          'please_select_issue_product': 'ກະລຸນາເລືອກສິນຄ້າທີ່ມີບັນຫາ',
          'do_you_want_save_or_not': 'ທ່ານຕ້ອງການບັນທຶກ ຫຼື ບໍ່?',
          'return': 'ສົ່ງຄືນ',
          'received_money': 'ຮັບເງິນແລ້ວ',
          'check_before_confirm': 'ກວດຄືນກ່ອນຢືນຢັນເຄື່ອງອອກ',
          'unauthorized_action': 'ບໍ່ໄດ້ຮັບອະນຸຍາດເຂົ້າເຖິງ.',
          'check_before_receive_money': 'ກວດຄືນກ່ອນກົດຮັບເງິນ',
          'receive_money': 'ຮັບເງິນ',
          'check_before_confirm_success': 'ກວດຄືນກ່ອນຢືນຢັນສໍາເລັດ',
          'product_warehouse': 'ສາງຜະລິດ',
          'number_production': 'ຈໍານວນຜະລິດ',
          'issue': 'ມີບັນຫາ',
          'Choose_problem_product': 'ເລືອກສິນຄ້າມີບັນຫາ',
          'delivery_person': 'ຄົນສົ່ງເຄື່ອງ',
          'Tuition_fees': 'ຄ່າຮຽນ',
          'score': 'ຄະແນນ',
          'student': 'ນັກຮຽນ',
          'total_paid': 'ຍອດຊໍາລະ',
          'total_debt': 'ຍອດຄ້າງຊໍາລະ',
          'ok': 'ຕົກລົງ',
          'logouts_successfully': 'ອອກຈາກລະບົບສຳເລັດ',
          'create_date': 'ວັນທີສ້າງ',
          'label_code': 'ລະຫັດປ້າຍ',
          'special_discount': 'ສ່ວນຫຼຸດພິເສດ',
          'school_mina': 'ໂຮງຮຽນ ມີນາ',
          'age': 'ອາຍຸ',
          'birtdaydate': 'ວັນ/ເດືອນ/ປີເກີດ',
          'class': 'ຫ້ອງຮຽນ',
          'missing_school': 'ຂາດໂຮງຮຽນ',
          'activities': 'ກິດຈະກຳ',
          'code_bill': 'ລະຫັດບິນ',
          'password_do_not_match': 'ລະຫັດຜ່ານບໍ່ກົງກັນ',
          'select': 'ເລືອກ',
          'select_year': 'ເລືອກປີ',
          'select_month': 'ເລືອກເດືອນ',
          'camera': 'ກ້ອງຖ່າຍຮູບ',
          'gallery': 'ຮູບພາບ',
          'corrected_successfully': 'ແກ້ໄຂສຳເລັດແລ້ວ',
          'invalid_phone_number_or_password_please_try_again':
              'ເບີໂທລະສັບ ຫຼື ລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ! ກະລຸນາລອງອີກຄັ້ງ...',
          'class_room': 'ຫ້ອງຮຽນ',
          'not_yet': 'ຍັງເທື່ອ',
          'waiting_confirm': 'ລໍຖ້າອານຸມັດ',
          'got_it': 'ຮັບເເລ້ວ',
          'give_money': 'ມອບຮັບເງິນ',
          'administration': 'ບໍລິຫານ',
          'subject': 'ວິຊາ',
          'start_pay': 'ເລີ່ມຈ່າຍ',
          'end_pay': 'ຄົບກຳນົດ',
          'email': 'ອິເມວ',
          'gender': 'ເພດ',
          'other': 'ອື່ນໆ',
          'select_classe': 'ເລືອກຫ້ອງຮຽນ',
          'select_subject': 'ເລືອກວິຊາ',
          'score_added_successfully': 'ເພີ່ມຄະແນນສຳເລັດແລ້ວ',
          'please_select_subject_first': 'ກະລຸນາ ເລືອກວິຊາກ່ອນ',
          'please_add_information': 'ກະລຸນາເພີ່ມຂໍ້ມູນ.',
          'please_enter_complete_information': 'ກະລຸນາໃສ່ຂໍ້ມູນຄົບຖ້ວນ!',
          'develop': 'ກຳລັງພັດທະນາ!',
          'add_information': 'ເພີ່ມຂໍ້ມູນ!',
          'monthly': 'ປະຈຳເດືອນ',
          'no': 'ຈັດທີ',
          'setting': 'ຕັ້ງຄ່າ',
          'childrens_score': 'ຄະແນນຂອງລູກ',
          'score_details': '​ຄະ​ແນນ​ປະ​ຈໍາ​ເດືອນ​',
          'teacher': 'ອາຈານ',
          'music': 'ດົນຕີ',
          'drawing': 'ການແຕ້ມຮູບ',
          'computer': 'ຄອມພິວເຕີ',
          'account': 'ບັນຊີ',
          'total_score': 'ຄະແນນລວມ',
          'average_score': 'ຄະແນນສະເລ່ຍ',
          'edit_profile': 'ແກ້ໄຂໂປຣໄຟລ໌',
          'upload_photo': 'ອັບໂຫຼດຮູບ',
          'delete': 'ລຶບ',
          'are_you_sure_you_want_to_delete_this_item':
              'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບລາຍການນີ້?',
          'confirm_delete': 'ຢືນຢັນການລຶບ',
          'select_student': 'ເລືອກນັກຮຽນ',
          'select_type': 'ເລືອກປະເພດ',
          'dated': 'ລົງວັນທີ',
          'score_cut_out': 'ຄະແນນຖືກຕັດ',
          'reset': 'ຣີເຊັດ',
          'date_is_required': 'ຕ້ອງການວັນທີ!',
          'follow_lack_off': 'ຕິດຕາມວັນຂາດການ',
          'follow_lack_off_details': 'ລາຍລະອຽດຕິດຕາມວັນຂາດຮຽນ',
          'student_name': 'ຊື່ນັກຮຽນ',
          'type': 'ປະເພດ',
          'creator': 'ຜູ້ສ້າງ',
          'total_score_cut_out': 'ລວມຄະແນນຖືກຕັດ',
          'missing_the_morning': 'ຂາດຕອນເຊົ້າ',
          'missing_evening': 'ຂາດຕອນແລງ',
          'missing_all_day': 'ຂາດໝົດມື້',
          'classe': 'ຫ້ອງຮຽນ',
          'parent': 'ຜູ້ປົກຄອງ',
          'search_month_year': 'ຄົ້ນຫາເດືອນປີ',
          'Payment_amount': 'ຈໍານວນເງິນຊໍາລະ',
          'transfer': 'ເງິນໂອນ',
          'take_children': 'ເອີ້ນ-ຮັບລູກ',
          'Missing_school': 'ຂາດຮຽນ',
          'Pay_tuition_fees': 'ຊໍາລະຄ່າຮຽນ',
          'payment_history': 'ປະຫວັດການຊຳລະຜ່ານມາ',
          'notification': 'ແຈ້ງເຕືອນ',
          'waiting': 'ລໍຖ້າ',
          'car_number': 'ປ້າຍລົດ',
          'delete_successfully': 'ລຶບສຳເລັດແລ້ວ.',
          'no_information_found': 'ບໍ່ພົບຂໍ້ມູນ.',
          'update_failed': 'ອັບເດດລົ້ມເຫລວ.',
          'Select_child_adopt': 'ເລືອກລູກທີ່ຈະຮັບ',
          'call_children': 'ເອີ້ນລູກ',
          'download': 'ດາວໂຫຼດ',
          'Please_scan_the_QRCode_to_pay_your_tuition':
              'ກະລຸນາ ສະແກນ QRCode ເພື່ອຊໍາລະຄ່າຮຽນ',
          'Waiting_for_payment': 'ລໍຖ້າການຊໍາລະເງິນ',
          'check_student': 'ກວດການັກຮຽນ',
          'sorry': 'ຂໍອະໄພ',
          'No_data_in_the_system': 'ບໍ່ມີຂໍ້ມູນໃນລະບົບ',
          'called': 'ເອີ້ນແລ້ວ',
          'No_information_yet': 'ຍັງບໍ່ມີຂໍ້ມູນ',
          'Get_discount_policy': 'ໄດ້ຮັບນະໂຍບາຍສ່ວນຫຼຸດ',
          'school': 'ໂຮງຮຽນ',
          'select_school': 'ເລືອກໂຮງຮຽນ',
          'nick_name': 'ຊື່ຫຼິ້ນ',
          'send_students': 'ສົ່ງນັກຮຽນ',
          'religion': 'ສາສະໜາ',
          'nationality': 'ສັນຊາດ',
          'group_language': 'ກຸ່ມພາສາ',
          'ethnicity': 'ເຜົ່າ',
          'special_health': 'ຈຸດພິເສດດ້ານສຸຂະພາບ',
          'personal_talent': 'ພອນສະຫວັນສ່ວນຕົວ',
          'living': 'ບ່ອນຢູ່ອາໄສ',
          'parent_data': 'ຂໍ້ມູນຜູ້ປົກຄອງ (ຊື່, ທີ່ຢູ່...)',
          'parent_contact':
              'ຂໍ້ມູນຕິດຕໍ່ຜູ້ປົກຄອງ (ເບີໂທ, ແອັບ, ເຟດບຸກ, ອີເມວ...)',
          'or': 'ຫຼື',
          'SelectClass_group': 'ເລືອກຊັ້ນຮຽນ',
          'Select_Class': 'ເລືອກຫ້ອງຮຽນ',
          'people': 'ຄົນ',
          'income': 'ລາຍຮັບ',
          'expenses': 'ລາຍຈ່າຍ',
          'balance_income': 'ດຸ່ນດຽງ',
          'opened': 'ເປີດແລ້ວ',
          'closed': 'ປິດແລ້ວ',
          'outstanding_tuition_fees': 'ຄ້າງຊໍາລະ',
          'select_package': 'ເລືອກແພັກເກັດ',
          'school_name': 'ຊື່ໂຮງຮຽນ',
          'School_owner': 'ເຈົ້າຂອງໂຮງຮຽນ',
          'Not_Found_QR_Code_Payment': 'ບໍ່ພົບ QR Code Payment',
          'Start_paying': 'ເລີ່ມຈ່າຍ',
          'Due_date': 'ຄົບກໍານົດ',
          'Contract_renewal': 'ຕໍ່ສັນຍາ',
          'price': 'ລາຄາ',
          'Blood_type': 'ໝວດເລືອດ',
          'Education_system': 'ລະບົບການສຶກສາ',
          'Education_level': 'ລະດັບການສຶກສາ',
          'Specialization': 'ວິຊາສະເພາະ',
          'Graduated_from_school': 'ຈົບຈາກໂຮງຮຽນ',
          'School year system': 'ລະບົບປີຮຽນ',
          'End_of_the_year': 'ຈົບປີ',
          'Duties': 'ໜ້າທີ່',
          'salary': 'ເງິນເດືອນ',
          'job': 'ອາຊີບ',
          'job_address': 'ບ່ອນເຮັດວຽກ',
          'job_position': 'ຕໍາແໜ່ງວຽກ',
          'select_pay': 'ເລືອກຊໍາລະ',
          'QR_code_download_complete': 'ດາວໂຫຼດ QR code ສໍາເລັດແລ້ວ',
          'Destination_bank': 'ທະນາຄານປາຍທາງ',
          'LAPNet_reference_number': 'ເລກອ້າງອີງ LAPNet',
          'version': 'ເວີຊັນ',
          'Delete_Account': 'ລຶບບັນຊີ',
          'Confirm_Account_Deletion': 'ຢືນຢັນການລຶບບັນຊີ',
          'des_confirm_delete_account':
              'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບບັນຊີຂອງທ່ານຢ່າງຖາວອນ? ຖ້າກົດລຶບ ຂໍ້ມູນຈະບໍ່ສາມາດກູ້ຄືນໄດ້.',
          'total_income': 'ລວມລາຍຮັບທັງໝົດ',
          'Contract_management': 'ຄຸ້ມຄອງສັນຍາ',
          'check_payment': 'ກວດສອບຊໍາລະເງິນ',
          'QR_Code_valid_within_hour': 'QR Code ໃຊ້ໄດ້ພາຍໃນ 1 ຊົ່ວໂມງ',
          'This_bill_has_not_been_paid_yet': 'ໃບບິນນີ້ ຍັງບໍ່ໄດ້ຊໍາລະເງິນ',
          'Track_absences': 'ຕິດຕາມວັນຂາດຮຽນ',
          'Still_left': 'ຍັງເຫຼືອ',
          'Minute': 'ນາທີ',
          'Seconds': 'ວິນາທີ',
          'bill_number': 'ເລກໃບບິນ',
          'Adjust': 'ປັບເພີ່ມ',
          'Please_pay_the_tuition_fee': 'ກະລຸນາ ຊໍາລະຄ່າຮຽນ',
          'Total_income_plan': 'ແຜນລາຍຮັບທັງໝົດ',
          'Do_you_want_to_allow_new_notifications': 'ທ່ານຕ້ອງການ ອະນຸຍາດ ເປີດແຈ້ງເຕືອນໃໝ່ບໍ',
          'transaction': 'ທຸລະກໍາ',
          'scan-in-out': 'ສະແກນເຂົ້າ-ອອກ',
          'check_in': 'ກວດເຂົ້າ',
          'check_out': 'ກວດອອກ',
          'request_go_home': 'ຂໍກັບບ້ານ',
          'who_go_with': 'ເລືອກຜູ້ທີ່ນັກຮຽນໄປກັບ',
          'time_in': 'ເວລາເຂົ້າ',
          'time_out': 'ເວລາອອກ',
          'mark-student':'ໝາຍຂາດນັກຮຽນ',
          'Click_in-out': 'ກົດ ເຂົ້າ-ອອກ',
          'your_current_position': 'ຕໍາແໜ່ງຂອງທ່ານ',
          'academic_year': 'ສົກຮຽນ',
          'scan': 'ສະແກນ',
          'history_missing_school': 'ປະຫວັດຂາດຮຽນ',
          'check_in_check_out': 'ເຂົ້າ-ອອກໂຮງຮຽນ',
          'scan_in': 'ສະເເກນເຂົ້າ',
          'IN': 'ເຂົ້າ',
          'OUT': 'ອອກ',
          'aLl_score': 'ຄະແນນຄຸນສົມບັດທັງໝົດ',
          'score_cuted': 'ລວມຄະແນນຖືກຕັດ',
        },
        'la_CN': {
          'login': '登入',
          'register': '登记',
          'home': '主页',
          'profile': '轮廓',
          'history': '历史',
          'all_purchase': '订单总额',
          'all_sell': '总销售额',
          'employee': '职员',
          'change_language': '更改语言',
          'do_you_want_to_logout': '您想退出吗？?',
          'cancel': '取消',
          'confirm': '确认',
          'total': '全部',
          'items': '项目',
          'qty': '数字',
          'total_money': '总金额',
          'date': '日期',
          'day': '天',
          'month': '月',
          'year': '年',
          'start_date': '开始日期',
          'end_date': '结束日期',
          'bill_no': '帐单代码',
          'payment_type': '付款方式',
          'cash': '现金',
          'bank_transfer': '划款',
          'search': '搜索',
          'customer': '顾客',
          'not_account': '还没有帐户*',
          'has_account': '或有一个帐户*',
          'password': '密码',
          'phone': '电话号码',
          'village': '村庄',
          'district': '区',
          'province': '省',
          'username': '系统用户名',
          'edit': '编辑',
          'firstname': '姓名',
          'lastname': '姓',
          'confirm_password': '确认密码',
          'new_product': '新产品',
          'advice_product': 'ສິນຄ້າແນະນໍາ',
          'all_product': 'ສິນຄ້າທັງໝົດ',
          'lak': '基普',
          'not_found_data': '还没有信息',
          'new': '新的',
          'order_list': 'ລາຍການສັ່ງຈອງ',
          'checkout': '支付',
          'please_enter_all': '请输入完整信息',
          'password_not_match': '验证码无效',
          'something_went_wrong': '有问题',
          'logout': '登出',
          'prefix': '先生女士',
          'phone_is_already': '该电话号码已在系统中',
          'success': '完全的',
          'phone_or_password_incorrect': '电话号码或密码无效!',
          'lao': '老挝',
          'english': '英格兰',
          'username_id_already': '该用户名已存在于系统中',
          'grand_total': '总金额',
          'choose_current_address': 'ເລືອກທີ່ຢູ່ປັດຈຸບັນ',
          'fullname': '名和姓',
          'thank_you': '谢谢',
          'back': '返回',
          'booking': 'ສັ່ງຈອງໃໝ່',
          'detail': '细节',
          'add_to_cart': 'ເພີ່ມເຂົ້າກະຕ່າ',
          'popular_product': 'ສິນຄ້າຍອດນິຍົມ',
          'save_qrcode_sn': 'ບັນທຶກ QRCODE SN',
          'use_current_address': '使用当前地址',
          'branch': '分支',
          'booking_list': 'ລາຍການສັ່ງຈອງ',
          'detail_booking': 'ລາຍລະອຽດສັ່ງຈອງ',
          'scan_out': '扫描出',
          'confirm_sale': 'ຢືນຢັນຂາຍ',
          'qrcode_sn_multiple': 'QRCODE SN ຊໍ້າກັນ',
          'can_not_scan_out_full_serial_number': 'ຈໍານວນ QRCODE SN ຄົບແລ້ວ',
          'product_list': 'Product',
          'delivery': 'ກໍາລັງຈັດສົ່ງ',
          'do_you_want_to_confirm_sale_or_not':
              'ທ່ານຕ້ອງການຢຶນຢັນຂາຍ ນີ້ ຫຼື ບໍ່?',
          'bill_get_money': 'ໃບບີນເກັບເງິນ',
          'thankyou': 'ຂໍຂອບໃຈທີ່ທ່ານມາອຸດໜູນ',
          'staff': 'ພະນັກງານ',
          'do_you_want_to_confirm': '你到底要确认还是不要确认？',
          'please_scan_qrcode_sn_full': 'ກະລຸນາສະແກນ QRCODE SN ໃຫ້ຄົບກ່ອນ!',
          'to': 'ຫາ',
          'do_you_want_to_confirm_delete_serial_number':
              'ທ່ານຕ້ອງການລຶບ QRCODE SN ນີ້ບໍ?',
          'all': '全部',
          'new_version_update_available': '有新版本更新了',
          'please_update_this_app_version': '请更新版本',
          'update': '更新',
          'location': 'ສະແດງແຜນທີ່',
          'scan_qrcode_sn': 'ສະແກນ QRCODE SN',
          'do_you_want_to_save_qrcode_sn': 'ທ່ານຕ້ອງການບັນທຶກ QRCODE SN ບໍ?',
          'approved': 'ອະນຸມັດແລ້ວ',
          'waiting_approve': 'ລໍຖ້າອະນຸມັດ',
          'please_select_customer': 'ກະລຸນາເລືອກລູກຄ້າ',
          'category': 'ໝວດໝູ່ສິນຄ້າ',
          'view_all': '查看全部',
          'select_branch': 'ເລືອກສາຂາ',
          'purchase_with_branch': 'ເຄີຍຊື້ຢູ່ສາຂາໃດ?',
          'please_select_branch': 'ກະລຸນາເລືອກສາຂາກ່ອນ',
          'type_of_use': 'ປະເພດການໃຊ້ງານ',
          'please_select_type_of_use': 'ກະລຸນາເລືອກປະເພດການໃຊ້ງານ',
          'select_customer': 'ເລືອກລູກຄ້າ',
          'male': '男性',
          'female': '女孩',
          'not_specify': '未指定',
          'product_detail': '产品详情',
          'welcome': '欢迎',
          'cn': '中国',
          'loan_goal': '贷款目标',
          'arrears_total': '欠款总额',
          'arrears': '欠款',
          'paid': '有薪酬的',
          'loan': '贷款',
          'instalment': '分期付款',
          'contact_us': '联系我们',
          'language': '语言',
          'product': '产品',
          'supplier': '供应商',
          'save': '节省',
          'select_payment_image': '选择付款方式',
          'picture_problem': '有问题的机器图片',
          'personal_information': '个人信息',
          'is_being_delivered': '正在交付中',
          'discount': '折扣',
          'thb': '铢',
          'usd': '美元',
          'cny': '元',
          'address': '地址',
          'payment': '支付',
          'add_picture_problem': '添加图片问题',
          'amount': '数量',
          'currency': '货币',
          'money_return': '退款',
          'Select_payment_currency': '选择支付货币',
          'add_payment': '添加付款',
          'balance': '平衡',
          'next': '下一个',
          'ordered': '已订购',
          'packed': '包装好的',
          'shipped': '已发货',
          'delivered': '发表',
          'Add_prepayment': '添加预付款',
          'Add_the_problem_image': '添加问题图片',
          'slip_payment': '付款单',
          'problem_image': '问题图像',
          'Send_machine': '送机器',
          'due': '到期的',
          'partial': '部分的',
          'status': '地位',
          'profit': '利润',
          'note': '笔记',
          'current_stock': '当前库存',
          'selling_price': '售价',
          'failed': '失败',
          'sent': '发送',
          'please_select_issue_product': '请选择有问题的产品',
          'return': '返回',
          'do_you_want_save_or_not': '你想保存还是不想保存？',
          'received_money': '收到钱了',
          'check_before_confirm': '确认前请先检查',
          'unauthorized_action': '未经授权的行为.',
          'check_before_receive_money': '收款前检查',
          'receive_money': '收到钱',
          'check_before_confirm_success': '确认前请先检查',
          'product_warehouse': '生产仓库',
          'number_production': '生产数量',
          'issue': '问题',
          'Choose_problem_product': '选择有问题的产品',
          'delivery_person': '快递送货员',
          'Tuition_fees': '学费',
          'score': '分数',
          'student': '学生',
          'total_paid': '付款余额',
          'total_debt': '欠款',
          'select': '选择',
          'select_year': '选择年份',
          'upload_photo': '上传照片',
          'delete': '删除',
          'are_you_sure_you_want_to_delete_this_item': '您确定要删除此项目吗？',
          'confirm_delete': '确认删除',
          'select_student': '选择学生',
          'select_type': '选择类型',
          'dated': '日期',
          'score_cut_out': '分数扣除',
          'reset': '重置',
          'date_is_required': '日期是必填项！',
          'follow_lack_off': '跟进缺勤',
          'follow_lack_off_details': '缺勤追踪详情',
          'student_name': '学生姓名',
          'type': '类型',
          'creator': '创建者',
          'total_score_cut_out': '总扣分',
          'missing_the_morning': '缺席上午',
          'missing_evening': '缺席下午',
          'missing_all_day': '缺席全天',
          'classe': '班级',
          'parent': '家长',
          'search_month_year': '按月份和年份搜索',
          'select_month': '选择月份',
          'Payment_amount': '付款金额',
          'transfer': '转移',
          'take_children': '带孩子',
          'Missing_school': '缺课',
          'setting': '环境',
          'code_bill': '代码法案',
          'Pay_tuition_fees': '缴纳学费',
          'payment_history': '付款历史记录',
          'special_discount': '特别折扣',
          'notification': '通知',
          'waiting': '等待',
          'car_number': '车号',
          'delete_successfully': '删除成功.',
          'no_information_found': '未找到任何信息.',
          'update_failed': '更新失败.',
          'Select_child_adopt': '选择一个孩子来收养。',
          'call_children': '呼唤孩子',
          'download': 'ດາວໂຫຼດ',
          'Please_scan_the_QRCode_to_pay_your_tuition': '请扫描二维码支付学费。',
          'Waiting_for_payment': '等待付款',
          'edit_profile': '编辑个人资料',
          'check_student': '检查学生',
          'sorry': '对不起。',
          'No_data_in_the_system': '系统中没有数据。',
          'called': '打电话',
          'No_information_yet': '尚无信息。',
          'Get_discount_policy': '获取折扣政策',
          'school': '学校',
          'select_school': '选择学校',
          'nick_name': '昵称',
          'send_students': '派遣学生',
          'religion': '宗教',
          'nationality': '国籍',
          'group_language': '语言群体',
          'ethnicity': '种族',
          'special_health': '健康特殊情况',
          'personal_talent': '个人才华',
          'living': '居住地',
          'parent_data': '家长信息（姓名、地址...）',
          'parent_contact': '家长联系方式（电话号码、应用程序、Facebook、电子邮件...）',
          'or': '或者',
          'SelectClass_group': '选择班级组',
          'Select_Class': '选择班级',
          'people': '人',
          'income': '收入',
          'expenses': '开支',
          'balance_income': '平衡',
          'opened': '已打开',
          'closed': '关闭',
          'outstanding_tuition_fees': '未缴学费',
          'no': '秩',
          'total_score': '总成绩',
          'average_score': '平均分数',
          'monthly': '每月',
          'score_details': '每月分数详情',
          'select_subject': '选择主题',
          'select_package': '选择套餐',
          'school_name': '学校名称',
          'School_owner': '学校老板',
          'Not_Found_QR_Code_Payment': '未找到二维码付款',
          'Start_paying': '开始付款',
          'Due_date': '到期日',
          'Contract_renewal': '合同续签',
          'price': '价格',
          'class': '班级',
          'age': '年龄',
          'label_code': '标签代码',
          'camera': '相机',
          'gallery': '画廊',
          'Blood_type': '血型',
          'Education_system': '教育体系',
          'Education_level': '教育水平',
          'Specialization': '专业',
          'Graduated_from_school': '毕业学校',
          'School year system': '学年制度',
          'End_of_the_year': '年终',
          'Duties': '职责',
          'salary': '薪资',
          'job': '工作',
          'job_address': '工作地址',
          'job_position': '工作职位',
          'select_pay': '选择支付',
          'QR_code_download_complete': '二维码付款下载完成',
          'Destination_bank': '目的地银行',
          'LAPNet_reference_number': 'LAPNet 参考编号',
          'version': '版本',
          'Delete_Account': '删除帐户',
          'Confirm_Account_Deletion': '确认删除帐户',
          'des_confirm_delete_account': '您确定要永久删除您的帐户吗？此操作无法撤消。',
          'total_income': '总收入',
          'Contract_management': '合同管理',
          'check_payment': '检查付款',
          'QR_Code_valid_within_hour': '二维码 1 小时内有效',
          'This_bill_has_not_been_paid_yet': '这张帐单还未付。',
          'Track_absences': '追踪缺勤情况',
          "Still_left": "仍然剩余",
          "Minute": "分钟",
          "Seconds": "秒",
          'bill_number': '账单号码',
          'Adjust': '调整',
          'Please_pay_the_tuition_fee': '请缴纳学费',
          'Total_income_plan': '总收入计划',
          'Do_you_want_to_allow_new_notifications': '您想允许新通知吗？',
          'transaction': '交易',
          'scan-in-out': 'ສະແກນເຂົ້າ-ອອກ',
          'check_in': '报到',
          'check_out': '查看',
          'request_go_home': '请求回家',
          'who_go_with': '选择学生与谁一起去。',
          'time_in': '时间',
          'time_out': '暂停',
          'mark-student':'Mark student',
          'Click_in-out': '点击进出',
          'your_current_position': '您的当前职位',
          'academic_year': '学年',
          'scan': '扫描',
          'history_missing_school': '缺课记录',
          'check_in_check_out': '进出学校',
          'scan_in': '扫码签到',
          'IN': '入',
          'OUT': '出',
          'aLl_score': '品德总分',
          'score_cuted': '扣分总计',
          'missing_school': '缺课'
        },
      };
}
