// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyD9rE76qGwc8YnW-dyVvHUCQ7KikHII8',
    appId: '1:19246411386:web:e089e95fd6a3bd9bca15c3',
    messagingSenderId: '19246411386',
    projectId: 'pathana-school-a6577',
    authDomain: 'pathana-school-a6577.firebaseapp.com',
    storageBucket: 'pathana-school-a6577.firebasestorage.app',
    measurementId: 'G-KPDZZCCGSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf5DKdu6Yi5HxMUVGeyGSmP6XNb1MPi8s',
    appId: '1:19246411386:android:10c7ceb8c162bd1cca15c3',
    messagingSenderId: '19246411386',
    projectId: 'pathana-school-a6577',
    storageBucket: 'pathana-school-a6577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl6BqjzJYCFU_Oy5n8HjxShfEHq2fBgDw',
    appId: '1:19246411386:ios:0a875ec3774b2067ca15c3',
    messagingSenderId: '19246411386',
    projectId: 'pathana-school-a6577',
    storageBucket: 'pathana-school-a6577.firebasestorage.app',
    iosBundleId: 'com.pathana.sSchool.App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl6BqjzJYCFU_Oy5n8HjxShfEHq2fBgDw',
    appId: '1:19246411386:ios:f205ab0c870cfe79ca15c3',
    messagingSenderId: '19246411386',
    projectId: 'pathana-school-a6577',
    storageBucket: 'pathana-school-a6577.firebasestorage.app',
    iosBundleId: 'com.sschoolapp.sSchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyD9rE76qGwc8YnW-dyVvHUCQ7KikHII8',
    appId: '1:19246411386:web:63079a7d4184f737ca15c3',
    messagingSenderId: '19246411386',
    projectId: 'pathana-school-a6577',
    authDomain: 'pathana-school-a6577.firebaseapp.com',
    storageBucket: 'pathana-school-a6577.firebasestorage.app',
    measurementId: 'G-TM29W996GY',
  );
}
