// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2_4lBBtNztxJiHIe4V-8jAfJ2usZOho',
    appId: '1:709794416722:web:757981df90f46e8e79778b',
    messagingSenderId: '709794416722',
    projectId: 'school-core',
    authDomain: 'school-core.firebaseapp.com',
    storageBucket: 'school-core.firebasestorage.app',
    measurementId: 'G-TM29W996GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwHwRPo2LQoPwHtv-TI5Qa3k4w5lS140',
    appId: '1:709794416722:android:dbac21bb8624620f79778b',
    messagingSenderId: '709794416722',
    projectId: 'school-core',
    storageBucket: 'school-core.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeIMmFTuXBRpSbh0CjUJ-CB8QGxYyusRo',
    appId: '1:709794416722:ios:9f5e805bf28cbcb979778b',
    messagingSenderId: '709794416722',
    projectId: 'school-core',
    storageBucket: 'school-core.firebasestorage.app',
    iosBundleId: 'com.sschoolapp.sSchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeIMmFTuXBRpSbh0CjUJ-CB8QGxYyusRo',
    appId: '1:709794416722:ios:9f5e805bf28cbcb979778b',
    messagingSenderId: '709794416722',
    projectId: 'school-core',
    storageBucket: 'school-core.firebasestorage.app',
    iosBundleId: 'com.sschoolapp.sSchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB2_4lBBtNztxJiHIe4V-8jAfJ2usZOho',
    appId: '1:709794416722:web:d45c84481340792979778b',
    messagingSenderId: '709794416722',
    projectId: 'school-core',
    authDomain: 'school-core.firebaseapp.com',
    storageBucket: 'school-core.firebasestorage.app',
    measurementId: 'G-TM29W996GY',
  );
}
